### ISSUE TITLE
Did you publish the repo to NPM?

### ISSUE THREAD

**Issue by yairEO** [swissspidy/local-webfont#1]
Running the code shows this error:

    npm ERR! 404 Not Found: local-webfont@latest

**Comment by swissspidy** [comment]
Heya, sorry I didn't see your issue here earlier.

I haven't published this to npm, so installation currently only works by manually adding the GitHub repo URL. Happy to add it though if it makes lives easier.

**Comment by yairEO** [comment]
So why did you write in the [usage section](https://github.com/swissspidy/local-webfont#usage) to use `npx` if you never even published it. It is unfathomable.

**Comment by swissspidy** [comment]
Apologies if this caused you troubles

**Comment by yairEO** [comment]
such a polite response :) a true politician

**Comment by swissspidy** [comment]
@yairEO Heya, I published the package to NPM now. It's available here:

https://www.npmjs.com/package/local-webfont

Sorry for the delay!
