### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by puremana** [swissspidy/local-webfont#2]
I get this `Path must be a string. Received undefined` error despite the result, successful or not.

![image](https://user-images.githubusercontent.com/2869411/54716761-652e2000-4bbb-11e9-9d4c-6d2b352ed6b3.png)

This occurs using your example usage too.

Great work on the package though!

**Comment by swissspidy** [comment]
Thanks for your report!

I just found https://github.com/zkat/npx/issues/144 about this error message. Are you using Node 10?

**Comment by puremana** [comment]
v8.11.3

**Comment by puremana** [comment]
Not an issue with your package then, sorry about that!
